[project]
name = "langchain-personal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain[openai]>=0.3.20",
    "langsmith>=0.3.13",
    "python-dotenv>=1.0.1",
]
